-- MySQL Script generated by MySQL Workbench
-- Tue Mar 11 22:26:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`genders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genders` (
  `gnd_id` INT NOT NULL AUTO_INCREMENT,
  `gnd_name` VARCHAR(45) NULL,
  PRIMARY KEY (`gnd_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`phoneTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`phoneTypes` (
  `pht_id` INT NOT NULL AUTO_INCREMENT,
  `pht_name` VARCHAR(45) NULL,
  PRIMARY KEY (`pht_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customers` (
  `cst_id` INT NOT NULL AUTO_INCREMENT,
  `cst_name` VARCHAR(255) NOT NULL,
  `cst_lastname` VARCHAR(45) NULL,
  `cst_birthdate` TIMESTAMP(6) NULL,
  `cst_phoneddd` VARCHAR(45) NULL,
  `cst_phonenumber` VARCHAR(45) NULL,
  `cst_document` VARCHAR(45) NULL,
  `cst_email` VARCHAR(45) NULL,
  `cst_password` VARCHAR(45) NULL,
  `cst_ranking` VARCHAR(45) NULL,
  `cst_gnd_id` INT NOT NULL,
  `cst_ptyp_id` INT NOT NULL,
  PRIMARY KEY (`cst_id`),
  INDEX `fk_Customers_Genders1_idx` (`cst_gnd_id` ASC) VISIBLE,
  INDEX `fk_Customers_PhoneTypes1_idx` (`cst_ptyp_id` ASC) VISIBLE,
  CONSTRAINT `fk_Customers_Genders1`
    FOREIGN KEY (`cst_gnd_id`)
    REFERENCES `mydb`.`genders` (`gnd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customers_PhoneTypes1`
    FOREIGN KEY (`cst_ptyp_id`)
    REFERENCES `mydb`.`phoneTypes` (`pht_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`addresses` (
  `add_id` INT NOT NULL AUTO_INCREMENT,
  `add_cst_id` VARCHAR(45) NULL,
  `add_trsd_id` VARCHAR(45) NULL,
  `add_trsd_name` VARCHAR(45) NULL,
  `add_streettype` VARCHAR(45) NULL,
  `add_street` VARCHAR(45) NULL,
  `add_number` VARCHAR(45) NULL,
  `add_complement` VARCHAR(45) NULL,
  `add_neighborhood` VARCHAR(45) NULL,
  `add_city` VARCHAR(45) NULL,
  `add_state` VARCHAR(45) NULL,
  `add_country` VARCHAR(45) NULL,
  PRIMARY KEY (`add_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customersAddresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customersAddresses` (
  `ca_cst_id` INT NOT NULL,
  `ca_add_id` INT NOT NULL,
  `ca_defaultshipping` VARCHAR(45) NULL,
  `ca_defaultbilling` VARCHAR(45) NULL,
  PRIMARY KEY (`ca_cst_id`, `ca_add_id`),
  INDEX `fk_Customers_has_Addresses_Addresses1_idx` (`ca_add_id` ASC) VISIBLE,
  INDEX `fk_Customers_has_Addresses_Customers_idx` (`ca_cst_id` ASC) VISIBLE,
  CONSTRAINT `fk_Customers_has_Addresses_Customers`
    FOREIGN KEY (`ca_cst_id`)
    REFERENCES `mydb`.`customers` (`cst_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customers_has_Addresses_Addresses1`
    FOREIGN KEY (`ca_add_id`)
    REFERENCES `mydb`.`addresses` (`add_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cardFlags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cardFlags` (
  `crf_id` INT NOT NULL AUTO_INCREMENT,
  `crf_name` VARCHAR(45) NULL,
  PRIMARY KEY (`crf_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paymentMethods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paymentMethods` (
  `pmm_id` INT NOT NULL AUTO_INCREMENT,
  `pmm_cardnumber` VARCHAR(45) NULL,
  `pmm_cardname` VARCHAR(45) NULL,
  `pmm_cvv` VARCHAR(45) NULL,
  `pmm_cst_id` INT NOT NULL,
  `pmm_crdf_id` INT NOT NULL,
  PRIMARY KEY (`pmm_id`),
  INDEX `fk_PaymentMethods_Customers1_idx` (`pmm_cst_id` ASC) VISIBLE,
  INDEX `fk_PaymentMethods_CardFlags1_idx` (`pmm_crdf_id` ASC) VISIBLE,
  CONSTRAINT `fk_PaymentMethods_Customers1`
    FOREIGN KEY (`pmm_cst_id`)
    REFERENCES `mydb`.`customers` (`cst_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PaymentMethods_CardFlags1`
    FOREIGN KEY (`pmm_crdf_id`)
    REFERENCES `mydb`.`cardFlags` (`crf_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`publishers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`publishers` (
  `pbl_id` INT NOT NULL AUTO_INCREMENT,
  `pbl_name` VARCHAR(45) NULL,
  PRIMARY KEY (`pbl_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pricingGroups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pricingGroups` (
  `pgrp_id` INT NOT NULL AUTO_INCREMENT,
  `pgp_name` VARCHAR(45) NULL,
  `pgp_percentage` VARCHAR(45) NULL,
  PRIMARY KEY (`pgrp_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`books` (
  `bok_id` INT NOT NULL AUTO_INCREMENT,
  `bok_year` VARCHAR(45) NULL,
  `bok_title` VARCHAR(45) NULL,
  `bok_edition` VARCHAR(45) NULL,
  `bok_isbn` VARCHAR(45) NULL,
  `bok_pages` VARCHAR(45) NULL,
  `bok_synopsis` LONGTEXT NULL,
  `bok_barcode` VARCHAR(45) NULL,
  `bok_pbl_id` INT NOT NULL,
  `bok_pgrp_id` INT NOT NULL,
  PRIMARY KEY (`bok_id`),
  INDEX `fk_Books_Publishers1_idx` (`bok_pbl_id` ASC) VISIBLE,
  INDEX `fk_Books_PricingGroups1_idx` (`bok_pgrp_id` ASC) VISIBLE,
  CONSTRAINT `fk_Books_Publishers1`
    FOREIGN KEY (`bok_pbl_id`)
    REFERENCES `mydb`.`publishers` (`pbl_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Books_PricingGroups1`
    FOREIGN KEY (`bok_pgrp_id`)
    REFERENCES `mydb`.`pricingGroups` (`pgrp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `ctg_id` INT NOT NULL AUTO_INCREMENT,
  `ctg_name` VARCHAR(45) NULL,
  PRIMARY KEY (`ctg_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`booksCategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`booksCategories` (
  `bc_ctg_id` INT NOT NULL,
  `bc_bok_id` INT NOT NULL,
  PRIMARY KEY (`bc_ctg_id`, `bc_bok_id`),
  INDEX `fk_Categories_has_Books_Books1_idx` (`bc_bok_id` ASC) VISIBLE,
  INDEX `fk_Categories_has_Books_Categories1_idx` (`bc_ctg_id` ASC) VISIBLE,
  CONSTRAINT `fk_Categories_has_Books_Categories1`
    FOREIGN KEY (`bc_ctg_id`)
    REFERENCES `mydb`.`categories` (`ctg_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categories_has_Books_Books1`
    FOREIGN KEY (`bc_bok_id`)
    REFERENCES `mydb`.`books` (`bok_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`suppliers` (
  `spp_id` INT NOT NULL AUTO_INCREMENT,
  `spp_name` VARCHAR(45) NULL,
  PRIMARY KEY (`spp_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inventories` (
  `inv_id` INT NOT NULL AUTO_INCREMENT,
  `inv_availablequantity` INT NULL,
  `inv_commitedquantity` INT NULL,
  `inv_price` FLOAT NULL,
  `inv_entrydate` TIMESTAMP(11) NULL,
  `inv_bok_id` INT NOT NULL,
  `inv_spp_id` INT NOT NULL,
  PRIMARY KEY (`inv_id`),
  INDEX `fk_Inventories_Books1_idx` (`inv_bok_id` ASC) VISIBLE,
  INDEX `fk_Inventories_Suppliers1_idx` (`inv_spp_id` ASC) VISIBLE,
  CONSTRAINT `fk_Inventories_Books1`
    FOREIGN KEY (`inv_bok_id`)
    REFERENCES `mydb`.`books` (`bok_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inventories_Suppliers1`
    FOREIGN KEY (`inv_spp_id`)
    REFERENCES `mydb`.`suppliers` (`spp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sales` (
  `sal_id` INT NOT NULL AUTO_INCREMENT,
  `sal_status` VARCHAR(45) NULL,
  `sal_freight` FLOAT NULL,
  `sal_cst_id` INT NOT NULL,
  `sal_add_id` INT NOT NULL,
  PRIMARY KEY (`sal_id`),
  INDEX `fk_Purchases_Customers1_idx` (`sal_cst_id` ASC) VISIBLE,
  INDEX `fk_Sales_Addresses1_idx` (`sal_add_id` ASC) VISIBLE,
  CONSTRAINT `fk_Purchases_Customers1`
    FOREIGN KEY (`sal_cst_id`)
    REFERENCES `mydb`.`customers` (`cst_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sales_Addresses1`
    FOREIGN KEY (`sal_add_id`)
    REFERENCES `mydb`.`addresses` (`add_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`saleItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`saleItems` (
  `sali_id` INT NOT NULL AUTO_INCREMENT,
  `sali_status` VARCHAR(45) NULL,
  `sai_quantity` INT NULL,
  `sai_sal_id` INT NOT NULL,
  `sai_bok_id` INT NOT NULL,
  PRIMARY KEY (`sali_id`),
  INDEX `fk_Saleitems_Sales1_idx` (`sai_sal_id` ASC) VISIBLE,
  INDEX `fk_Saleitems_Books1_idx` (`sai_bok_id` ASC) VISIBLE,
  CONSTRAINT `fk_Saleitems_Sales1`
    FOREIGN KEY (`sai_sal_id`)
    REFERENCES `mydb`.`sales` (`sal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Saleitems_Books1`
    FOREIGN KEY (`sai_bok_id`)
    REFERENCES `mydb`.`books` (`bok_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`exchanges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exchanges` (
  `exc_id` INT NOT NULL,
  `exc_status` VARCHAR(45) NULL,
  `exc_sal_id` INT NOT NULL,
  PRIMARY KEY (`exc_id`),
  INDEX `fk_Exchanges_Sales1_idx` (`exc_sal_id` ASC) VISIBLE,
  CONSTRAINT `fk_Exchanges_Sales1`
    FOREIGN KEY (`exc_sal_id`)
    REFERENCES `mydb`.`sales` (`sal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`salesPaymentMethods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`salesPaymentMethods` (
  `spm_pmm_id` INT NOT NULL,
  `spm_sal_id` INT NOT NULL,
  `spm_value` FLOAT NULL,
  PRIMARY KEY (`spm_pmm_id`, `spm_sal_id`),
  INDEX `fk_PaymentMethods_has_Sales_Sales1_idx` (`spm_sal_id` ASC) VISIBLE,
  INDEX `fk_PaymentMethods_has_Sales_PaymentMethods1_idx` (`spm_pmm_id` ASC) VISIBLE,
  CONSTRAINT `fk_PaymentMethods_has_Sales_PaymentMethods1`
    FOREIGN KEY (`spm_pmm_id`)
    REFERENCES `mydb`.`paymentMethods` (`pmm_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PaymentMethods_has_Sales_Sales1`
    FOREIGN KEY (`spm_sal_id`)
    REFERENCES `mydb`.`sales` (`sal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`promotionalCoupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`promotionalCoupon` (
  `prmc_id` INT NOT NULL,
  `prmc_code` VARCHAR(45) NULL,
  `prmc_value` FLOAT NULL,
  PRIMARY KEY (`prmc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`salesPromotionalCoupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`salesPromotionalCoupon` (
  `spc_sal_id` INT NOT NULL,
  `spc_prmc_id` INT NOT NULL,
  PRIMARY KEY (`spc_sal_id`, `spc_prmc_id`),
  INDEX `fk_Sales_has_PromotionalCoupon_PromotionalCoupon1_idx` (`spc_prmc_id` ASC) VISIBLE,
  INDEX `fk_Sales_has_PromotionalCoupon_Sales1_idx` (`spc_sal_id` ASC) VISIBLE,
  CONSTRAINT `fk_Sales_has_PromotionalCoupon_Sales1`
    FOREIGN KEY (`spc_sal_id`)
    REFERENCES `mydb`.`sales` (`sal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sales_has_PromotionalCoupon_PromotionalCoupon1`
    FOREIGN KEY (`spc_prmc_id`)
    REFERENCES `mydb`.`promotionalCoupon` (`prmc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`exchangeItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exchangeItems` (
  `exi_id` INT NOT NULL,
  `exi_status` VARCHAR(45) NULL,
  `exi_exc_id` INT NOT NULL,
  `exi_sali_id` INT NOT NULL,
  PRIMARY KEY (`exi_id`),
  INDEX `fk_Exchangeitems_Exchanges1_idx` (`exi_exc_id` ASC) VISIBLE,
  INDEX `fk_Exchangeitems_Saleitems1_idx` (`exi_sali_id` ASC) VISIBLE,
  CONSTRAINT `fk_Exchangeitems_Exchanges1`
    FOREIGN KEY (`exi_exc_id`)
    REFERENCES `mydb`.`exchanges` (`exc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Exchangeitems_Saleitems1`
    FOREIGN KEY (`exi_sali_id`)
    REFERENCES `mydb`.`saleItems` (`sali_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

USE mydb;
INSERT INTO genders (gnd_name) VALUES ("MASCULINO");
INSERT INTO genders (gnd_name) VALUES ("FEMININO");
INSERT INTO genders (gnd_name) VALUES ("OUTRO");

INSERT INTO phoneTypes (pht_name) VALUES ("FIXO");
INSERT INTO phoneTypes (pht_name) VALUES ("CELULAR");